### ISSUE TITLE
Visual Studio 2013 build errors

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#1]
Please, add support for Visual Studio 2013 (at least, just in source, no binary releases required). It is not so old to be neglected. I've met error C3646: 'noexcept'. This keyword is absent in VS 2013.
Here are workarounds for inspiration:
https://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio

**Comment by Skycoder42** [comment]
I have no machine available with VS2013. You can create a PR for this if you want. I wasn't expecting any compiler to not support that, as it is C++11 (which is required by latest Qt).

There is a Qt macro for that, [`Q_DECL_NOTHROW`](https://doc.qt.io/qt-5/qtglobal.html#Q_DECL_NOTHROW). This way you can make shure the fix actually works. Simply replace it, e.g.: `void myFunc() noexcept` -> `void myFunc() Q_DECL_NOTHROW`. If you encounter other keywords vs2013 does not support, you can do the same for those with the other Qt macros

**Comment by arietto** [comment]
Thanks for your quick answer.  I have other template-related errors:
`d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(53) : error C2144: syntax error : 'bool' should be preceded by ';' (.\qjsonserializer.cpp)
        d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(58) : see reference to class template instantiation '_qjsonserializer_helpertypes::gadget_helper<T,Enable>' being compiled
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(53) : error C2144: syntax error : 'bool' should be preceded by ';' (.\qtjsonserializer_global.cpp)
        d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(58) : see reference to class template instantiation '_qjsonserializer_helpertypes::gadget_helper<T,Enable>' being compiled
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(53) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (.\qjsonserializer.cpp)
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(53) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (.\qtjsonserializer_global.cpp)
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(65) : error C2144: syntax error : 'bool' should be preceded by ';' (.\qjsonserializer.cpp)
        d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(70) : see reference to class template instantiation '_qjsonserializer_helpertypes::gadget_helper<T,T::QtGadgetHelper>' being compiled
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(65) : error C2144: syntax error : 'bool' should be preceded by ';' (.\qtjsonserializer_global.cpp)
        d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(70) : see reference to class template instantiation '_qjsonserializer_helpertypes::gadget_helper<T,T::QtGadgetHelper>' being compiled
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(65) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (.\qjsonserializer.cpp)
d:\projects\qtjsonserializer\include\qtjsonserializer\../../src/jsonserializer/qjsonserializer_helpertypes.h(65) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (.\qtjsonserializer_global.cpp)
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'`

**Comment by Skycoder42** [comment]
Okay, that looks bad. These errors seem to indicate that one ore more of the `type_traits` classes are missing. However, the template parts rely on those, so 2013 is just to old.

However, you might be able still get it to work by removing the template functions:
1. Remove/Delete the `qjsonserializer_helpertypes.h` header
2. In `qjsonserializer.h`, remove all template methods that make use of the helpertypes. (that should be various overloads of serialize, deserialize, serializeTo and deserializeFrom).

By doing so, you might be able to compile, but loose the ability to use the templates. This means you have to now work with `QVariant` and `QJsonValue` only. 

For example, this:
```
MyClass* data = ...;
QJsonObject o = serializer->serialize(data);
```
now becomes this:
```
MyClass* data = ...;
QJsonObject o = serializer->serialize(QVariant::fromValue<MyClass*>(data)).toObject();
```

**Comment by arietto** [comment]
Ok, I' ll try it, thanks. I suppose that it is better to use lite (cut for VS 2013) 3.1.0 version of your library, than 2.2.2 version (which is VS2013 friendly out-of-the-box) .

**Comment by Skycoder42** [comment]
I would recommend that, yes. The reason I had to use the new c++11 template stuff in the beginning is because in 2.* it did not work for all cases. Also I made some breaking changes internally. So with "3.1.0 lite" you are better of. It makes migration easier too, if you ever plan to update your compiler ;)

**Comment by Skycoder42** [comment]
If you manage to get it run, feel free to publish the lite version as an PR. I won't merge it, but reference it in the README, so others that use VS2013 can use that one as well.
