### ISSUE TITLE
How to register a custom complex type

### ISSUE THREAD

**Issue by darkgirl** [Skycoder42/QJsonSerializer#11]
in my program, i need some kind of type, like QMap<QString, QList<SaleProperty*>>
but no matter what i tried, it always crash

Here is whate i tried:
	qRegisterMetaType<QMap<QString, QList<SaleProperty*>>>("QMap<QString, QList<SaleProperty*>>");
	qRegisterMetaType<QMap<QString, QStringList>>("QMap<QString, QStringList>");
	qRegisterMetaType<QMap<QString, QList<QString>>>("QMap<QString, QList<QString>>");
	QJsonSerializer::registerAllConverters<QList<QString>>();
	QJsonSerializer::registerMapConverters<QList<SaleProperty*>>();
	QJsonSerializer::registerListConverters<SaleProperty*>();

I would be very grateful if you can provide some help.

**Comment by Skycoder42** [comment]
I am not shure where you went wrong, because your declarations at least include the correct declarations. The only ones you need are a list converter for the `SaleProperty` followed by a map converter for a list of those:

```
QJsonSerializer::registerListConverters<SaleProperty*>();
QJsonSerializer::registerMapConverters<QList<SaleProperty*>>();
```
`qRegisterMetaType` is not needed, as `QMap` and `QList` are already declared for any type, you only need a `Q_DECLARE_METATYPE(SaleProperty*)` In the header.

The libraries uses exceptions, so to find out what exactly goes wrong, you should try to catch and print them. The "quick and dirty" way is to just do so in the main:
```
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    try {
        // <Your code>
        return a.exec();
    } catch (QJsonSerializerException &e) {
        qCritical("%s", e.what());
        return 1;
    }
}
```

I created a basic demo project to check if there was actually some error in the library, but my test project worked as expected. I attached it so you can compare it with your code: [jserissue.zip](https://github.com/Skycoder42/QtJsonSerializer/files/2723324/jserissue.zip)

**Comment by adrobut** [comment]
Hello, 
    qRegisterMetaType<SaleProperty*>("SaleProperty*");
Before using it. 

Hope this will help,
Good luck!

**Comment by darkgirl** [comment]
> I am not shure where you went wrong, because your declarations at least include the correct declarations. The only ones you need are a list converter for the `SaleProperty` followed by a map converter for a list of those:
> 
> ```
> QJsonSerializer::registerListConverters<SaleProperty*>();
> QJsonSerializer::registerMapConverters<QList<SaleProperty*>>();
> ```
> `qRegisterMetaType` is not needed, as `QMap` and `QList` are already declared for any type, you only need a `Q_DECLARE_METATYPE(SaleProperty*)` In the header.
> 
> The libraries uses exceptions, so to find out what exactly goes wrong, you should try to catch and print them. The "quick and dirty" way is to just do so in the main:
> 
> ```
> int main(int argc, char *argv[])
> {
>     QCoreApplication a(argc, argv);
>     try {
>         // <Your code>
>         return a.exec();
>     } catch (QJsonSerializerException &e) {
>         qCritical("%s", e.what());
>         return 1;
>     }
> }
> ```
> I created a basic demo project to check if there was actually some error in the library, but my test project worked as expected. I attached it so you can compare it with your code: [jserissue.zip](https://github.com/Skycoder42/QtJsonSerializer/files/2723324/jserissue.zip)

Thanks a lot.
I checked my code again, and found that i was using Q_DECLARE_METATYPE(SaleProperty) in my header file, and when i changed it to Q_DECLARE_METATYPE(SaleProperty*), everything went well.

i do not usually use these advance macro, at first, i considered that pointer dose not seem to need specially declare after i read the README.md document. so i think, because of qt do not recognize self-define class so i use Q_DECLARE_METATYPE(SaleProperty) in my header file. is there anything i understand wrong?

is there anything i understand wrong?

**Comment by darkgirl** [comment]
> Hello,
> qRegisterMetaType<SaleProperty*>("SaleProperty*");
> Before using it.
> 
> Hope this will help,
> Good luck!


thank you for your help, and i also solved my problem, good luck

**Comment by Skycoder42** [comment]
`Q_DECLARE_METATYPE(SaleProperty)` is wrong in this context, if SaleProperty is a `Q_OBJECT`.

The rule is:
- Class extends `QObject` and has the `Q_OBJECT` macro -> Use `Q_DECLARE_METATYPE(MyClass*)`
- Class is a normal, value type class/struct and has the `Q_GADGET` macro -> use `Q_DECLARE_METATYPE(MyClass)`
- Generally speaking, register the type in the way you use it in your code

Whether registering is required or not often depends on the context and usage, and at least for this very basic example, it would not be strictly neccessary, but it's always good to use those macros anyway, as having them is always only beneficial.

I will close this issue know, but if you have further questions regarding this specific case, you can still reply to it.

**Comment by darkgirl** [comment]
> `Q_DECLARE_METATYPE(SaleProperty)` is wrong in this context, if SaleProperty is a `Q_OBJECT`.
> 
> The rule is:
> 
> * Class extends `QObject` and has the `Q_OBJECT` macro -> Use `Q_DECLARE_METATYPE(MyClass*)`
> * Class is a normal, value type class/struct and has the `Q_GADGET` macro -> use `Q_DECLARE_METATYPE(MyClass)`
> * Generally speaking, register the type in the way you use it in your code
> 
> Whether registering is required or not often depends on the context and usage, and at least for this very basic example, it would not be strictly neccessary, but it's always good to use those macros anyway, as having them is always only beneficial.
> 
> I will close this issue know, but if you have further questions regarding this specific case, you can still reply to it.

Thanks again, I've learned a lot from your help. Have a nice day
