### ISSUE TITLE
QSqlQuery And QSqlQueryModel

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [Skycoder42/QJsonSerializer#17]
**Any Example to Serialize QSqlQuery Or QSqlQueryModel**

**Comment by Skycoder42** [comment]
QSqlQuery is a very complex type and not easily serializable. It heavily depends on how much of the query you want to serialize. Do you only need the query string, or also possible arguments that have already been set. Do you want to include the result, selection state, drivers etc. 

Also, QSqlQuery needs to be constructed with a QSqlDatabase to properly work. Do you want to serialize the connection information of that database as well? Or only the name?

Those are just the basic question you need to answer to solve this. If you only need the pattern, simply convert it to a string and then serialize it. For all other cases, you have to implement a custom [QJsonTypeConverter](https://skycoder42.github.io/QtJsonSerializer/class_q_json_type_converter.html). The documentation gives a details explanation on how to use these. The details of the serialization however you have to figure out yourself, as again, there are way to many possiblities on what exactly you need to serialize.

The same applies for the QSqlQueryModel - what exactly do you want to serialize here?

**Comment by MrAhmedSayedAli** [comment]
My simple Code i used 
just serialize the result to sent it to TCP

QJsonDocument DataBase::toJson(const QString &sqlquery)
{
    QJsonDocument  json;
    QJsonArray     recordsArray;
    if(QSqlDatabase::contains(ConnName) == false){
        if(!dbConnact()){
            return json;
        }
    }
    QSqlQuery query(sqlquery,QSqlDatabase::database(ConnName));

    while(query.next()) {
        QJsonObject recordObject;
        for(int x=0; x < query.record().count(); x++) {
            recordObject.insert( query.record().fieldName(x), QJsonValue::fromVariant(query.value(x)) );
        }
        recordsArray.push_back(recordObject);
    }
    json.setArray(recordsArray);
    return json;
}

**Comment by Skycoder42** [comment]
So you want to serialize the *result* of a query. Your code seems to do that quite well.

To get the same result using this library, create a QJsonTypeConverter. In its implementation, you can put the code you showed here. Then you can register it to the serializer and serialize queries just like any other datatype

**Comment by Skycoder42** [comment]
You need any more help? If not, I will close this issue

**Comment by MrAhmedSayedAli** [comment]
no , you can close it , and thanx ^_^
