### ISSUE TITLE
Ignoring STORED attribute mode

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#18]
Hello! I think that sometimes it's helpful to have an ability to serialize properties even with STORED=false. 
For example, we save all properties for output in debug log and subset of properties with STORED=true for REST service response.

**Comment by Skycoder42** [comment]
Fair point. Simply having a property for that in the QJsonSerializer to enable/disable it per serializer sounds like a easy enough feature to implement.
