### ISSUE TITLE
GCC 4.7.2 build errors

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#2]
Hello! I have to use old GCC 4.7.2. Building your project leads to the following errors:
`In file included from qjsonserializerexception.cpp:1:0:
qjsonserializerexception.h:12:31: error: looser throw specifier for ‘virtual QJsonSerializerException::~QJsonSerializerException()’
In file included from /usr/lib/Qt5.9/include/QtCore/QtCore:56:0,
                 from ../../include/QtJsonSerializer/QtJsonSerializerDepends:3:
/usr/lib/Qt5.9/include/QtCore/qexception.h:62:5: error:   overriding ‘virtual QException::~QException() noexcept (true)’
make[2]: *** [.obj/qjsonserializerexception.o] Error 1
make[2]: Leaving directory `/home/user/QtJsonSerializer/src/jsonserializer'
make[1]: *** [sub-jsonserializer-make_first-ordered] Error 2
make[1]: Leaving directory `/home/user/QtJsonSerializer/src'
make: *** [sub-src-make_first] Error 2`

Tell me please, what is the workaround?

**Comment by Skycoder42** [comment]
Firstoff: It's very possible this compiler will not work, as I'm making use of C++11 features. I don't know how good the C++11 support of that gcc version is. If you encounter more errors, check #1 first, as the errors might be similar.

But regarding the error you have: Apparently, the compiler fails at generating the default destructor for [QJsonSerializerException](https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/qjsonserializerexception.h#L12).

As a workaround, you could try to add the destructur explicitly for the 3 classes with noexcept: `~QJsonSerializerException() noexcept`. (Same for the other 2 defined in the file).

**Comment by Skycoder42** [comment]
Could this solve your Problem?

**Comment by arietto** [comment]
Hello. Yes, your hint helped me solve the error.
