### ISSUE TITLE
Deserialize QObject* with parametrized constructor

### ISSUE THREAD

**Issue by milad-gh** [Skycoder42/QJsonSerializer#22]
Hello,
Is it technically possible to have Q_INVOKABLE constructor that takes some parameters when deserializing a QObject ??

**Comment by Skycoder42** [comment]
Not really, no. How would the serializer know what these parameters are? Do you want to deserialize some json properties as arguments for the constructor?

More details on your use case might help. If you have a class you cannot modify, I would recommend you to create a wrapper class that takes care of this.

**Comment by milad-gh** [comment]
Thanks for your reply,
The main issue is that i want to serialize/deserialize some QObject derived classes but this classes are logically dependent to each other, e.g class2 has a constructor that takes class1 as argument. and i want to serialize these two classes.
For serialization everything is OK but for deserialization after i deserialized class1, i want to pass it to class2 constructor when i'm constructing (desalinizing) class2.

Now i'm using a wrapper class as you mentioned, to handle these dependencies, but its a little bug prone because classes should have a setter methods rather than constructors.
i was wondering maybe its possible to have a none-default constructors for QObjects.

**Comment by Skycoder42** [comment]
It  is not possible with the current architecture. However, you can create your own [QJsonTypeConverter](https://skycoder42.github.io/QtJsonSerializer/class_q_json_type_converter.html) to handle this situation. 

Just create one by copying the code from [QJsonObjectConverter](https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/typeconverters/qjsonobjectconverter_p.h) and then adjust it to work the way you need it to. Just make sure to give it at least a `High` priority, so it is preferred to be used over the standard QObject converter.

**Comment by milad-gh** [comment]
Thanks for your help,
I'll try to use this approach.

**Comment by Skycoder42** [comment]
Any success yet? If yes, you can close the issue. If not, I might be able to give further help...

**Comment by milad-gh** [comment]
Actually i tried to redesign some part of my code without using QJsonObjectConverter, because i wanted to keep source code simple for now.
But it seems using QJsonObjectConverter is a robust approach for future.
I appreciate your help.
