### ISSUE TITLE
build source is ok but run example get the follow error for qt5.12.4 on macos

### ISSUE THREAD

**Issue by toby20130333** [Skycoder42/QJsonSerializer#26]
HI @Skycoder42 
I got the error with build example
I follow the command

qmake && make && make install

![image](https://user-images.githubusercontent.com/4186642/70197996-82eee580-1748-11ea-9d1b-789f752b62db.png)

**Comment by Skycoder42** [comment]
Those are all C++17 features - so apparently, the examples are missing the configuration arguments. I thought those would be derived from the library, but it seems they are not.

Try adding the following to the examples `pro` files:
```
CONFIG += c++17
QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.14 # has to be added because std::visit only works on macos 10.14 and above
```

**Comment by toby20130333** [comment]
@Skycoder42 thank you
