### ISSUE TITLE
QHash<int, QString> workaround

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#29]
Hello! Is it reasonable to represent QHash<int, QString> field as QVariantHash property (using getter/setter fo conversion)?

**Comment by Skycoder42** [comment]
yes, you can do this to avoid explicit registration of the hash converter. However, while it works for `QHash<int, QString>`, other type might not be implicitly convertible.

**Comment by arietto** [comment]
OK, thank you.
