### ISSUE TITLE
QVector support

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#3]
If the struct (Q_GADGETed) contains QVector<MyStruct>, what can be done in order to make your library work? I've read about registering QList's, but QVector is also very popular data structure. It is considered as a default choice in Qt5 docs (older Qt4 docs advertized QList).

**Comment by Skycoder42** [comment]
Not supported yet, but thanks to the change of 3.0, easy to implement.

Have a look at:
- https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/typeconverters/qjsonlistconverter_p.h
- https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/typeconverters/qjsonlistconverter.cpp

You can simply copy those files and replace `QList` with `QVector` in all the methods. It can be added to an instance using `QJsonSerializer::addJsonTypeConverter`

I will keep this issue open, and will add it in the next version.

**Comment by Skycoder42** [comment]
One one thing: In Order for that to actually work, you need to register converters from `QVector<T>` to `QVariantList` and back. Sadly, this must be done for every type T. Thats one of the reasons I only support `QList` for now. I register those converters for many standard Qt types, but doing that for any container would generate way to many symbols.

I decided to use QList, as of my knowledge, even in Qt5, this is the default container (It is primarily used by Qt classes, and stated as the "default" in here: https://doc.qt.io/qt-5/containers.html).

So most likely, I will **not** add QVector to the library. You can either create it yourself, as state before, or use the following workaround:

```
struct MyGadget {
    Q_GADGET

    Q_PROPERTY(QList<int> myInt READ getMyInt WRITE setMyInt)
    Q_PROPERTY(QVector<int> myInternalInt MEMBER _myInt STORED false) //will not be serialized

public:
    QVector<int> _myInt;

private:
    QList<int> getMyInt() const {
        return _myInt.toList();
    }
    void setMyInt(const QList<int> &list) {
        _myInt = QVector<int>::fromList(list);
    }
};
```
