### ISSUE TITLE
Mac build "make" step giving .reggen errors. Any advice?

### ISSUE THREAD

**Issue by sammykill** [Skycoder42/QJsonSerializer#32]
When I call make on 4.0.3 I'm getting this. I've built the last several versions and have never had this problem.

/Qt_Commercial/5.14.1/QtJsonSerializer-4.0.3/src/jsonserializer/qjsonreggen.py /Qt_Commercial/5.14.1/QtJsonSerializer-4.0.3/src/jsonserializer/.reggen/qjsonconverterreg_bool.cpp bool
env: python3: No such file or directory
make[2]: *** [/Qt_Commercial/5.14.1/QtJsonSerializer-4.0.3/src/jsonserializer/.reggen/qjsonconverterreg_bool.cpp] Error 127
make[1]: *** [sub-jsonserializer-make_first] Error 2
make: *** [sub-src-make_first] Error 2

**Comment by Skycoder42** [comment]
`env: python3: No such file or directory`

please install python, for example via [homebrew](https://brew.sh/): `brew install python`

**Comment by sammykill** [comment]
Great, thank you!
