### ISSUE TITLE
Using multiple instances in Qt subdir

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#34]
Hello! I have to use 3.x and 4.x versions of QtJsonSerializer in different projects.
The problem is that Qt subdir gcc_64/include/QtJsonSerializer/ contains headers which are different for 3.x and 4.x. Why don't these specific headers stay in 4.x and 3.x subdirs?  For example, jsonserializer.h.

**Comment by arietto** [comment]
In order to fight headers mess I have to set INSTALL_ROOT for make (custom install directory).
But the problem is with QtRestClient 3, it looks into Qt subdirectory for QtJsonSerializer and finds older version (3 instead of 4).

**Comment by Skycoder42** [comment]
I dont think this is possible with qt... You could duplicate the gcc_64

**Comment by arietto** [comment]
OK, thanks
