### ISSUE TITLE
CopperSpice support

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#42]
Hello! I have to switch to bare metal ARM (Xilinx Zynq-7000). 
I have plenty of PODs (Q_GADGET's) for JSON serialization.
I cannot use Qt for MCUs. Is it technically possible to adapt QtJsonSerializer for [CopperSpice](https://www.copperspice.com/) support? I mean using reduced version of CsCore and QtJsonSerializer for bare metal. Surely, I don't ask you to do this task, just want to know whether it requires a lot of work or is totally impossible.
P.S. Bare metal doesn't imply a memory size, it only means that there's no full-blown operating system.

**Comment by Skycoder42** [comment]
This library heavily relies on qmetaobject and all the other qt reflection mechanisms. Unless CopperSpice leverages a nearly identical API, a port will be very challenging...

**Comment by arietto** [comment]
OK, thank you.
