### ISSUE TITLE
Create references to existing object , not duplicates

### ISSUE THREAD

**Issue by loopless** [Skycoder42/QJsonSerializer#48]
Assuming I have some code like this
	QList<QSharedPointer<SampleObject>> aList;
	QSharedPointer<SampleObject> tmp(new SampleObject());
	aList.append(tmp);
	aList.append(tmp);
	auto jsonarray = serializer.serialize(aList);
	qDebug() << "\nSerialize a QList now:";
	qDebug() << JSON_PRINT(jsonarray);

Then the generated JSON has duplicates of the object. Clearly this will not restored as intended. 
The application code could use "names" or some other "ids" to prevent duplication as a workaround.
Just wondering if this has been thought of/dealt with by others.

**Comment by Skycoder42** [comment]
It works this way on purpose, as QObjects (which are pointers) are serialized from and to JSON. So smart pointer that wrap QObjects do the same, it just exists for convenience. Converting pointers from and to JSON is simply not possible, as you can't transform a reference.

**Comment by loopless** [comment]
Firstly, thanks for a great library. It's well written and super useful. 
I did not expect the library to magically handle references.
Creating object references rather than duplicate objects then has to be handled at an application level as a post processing step after reading the JSON. For example, have a 64-bit ID in each QObject and do a fix-up to re-use an existing object if the ID has previously been encountered.  Or something like that.

**Comment by Skycoder42** [comment]
In that case, you could write a custom converter and register it with a high priority for your pointers. See  https://skycoder42.github.io/QtJsonSerializer/class_qt_json_serializer_1_1_type_converter.html
