### ISSUE TITLE
Using pointer to gadget

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#5]
Hello! Is it possible to use pointer (or QSharedPointer) to Q_GADGET struct/class as a property for serialization in future? Please, see QMetaType::PointerToGadget:
https://git.qt.io/consulting-usa/qtbase-xcb-rendering/commit/30da659af5ff4ee33c22a3fc81801cdcbc57d535
What workaround can be applied in QJsonTypeConverter ancestor? I suppose that I have to use patched QMetaType...

**Comment by arietto** [comment]
Oh, it was introduced in Qt 5.10. Then you should add info about it to your manual. 
http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qmetatype.h?h=5.10

**Comment by Skycoder42** [comment]
Interesting. This can definitly be added in a future version. When I created this library, gadget pointers where not supported yet.

If you have the time, you can create a pull request for that. You will most likely have to adjust https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/typeconverters/qjsongadgetconverter.cpp sligthly so it can handle both versions, value and pointer gadgets, as the code to serialize the gadget itself wont change, just how to get the gadget from QVariant.

**Comment by arietto** [comment]
Ok, and what about Q_GADGET written as `QSharedPointer<MyGadget> m_gadget`? If I use special property for it (with custom getter/setter), then should I prefer `QJsonValue` over `QVariant` for properties to minimize intermediate conversions?

**Comment by Skycoder42** [comment]
Yes, you can of cause create a "dummy property" that returns a generic value and use it as a local converter.

If you do the conversion yourself, it doesn't matter that, as long as you only use "primitive variants" (i.e. QString, int, QVariantMap, QVariantList) - however I would recommend to use QJsonValue anyways, as this prevents you from accidentially returning a non trivial variant and makes it obvious what the methods do.

I typically use the following pattern:
```
Q_PROPERTY(QJsonValue myGadget READ getMyGadget WRITE setMyGadget)
// and optionally, if you still want to use the gadget from the property system
Q_PROPERTY(QSharedPointer<MyGadget> _myGadget MEMBER m_gadget STORED false)
```

**Comment by Skycoder42** [comment]
Support for plain gadget pointers was added. Smart gadget pointers are currently not supported by Qt, as `QMetaType::PointerToGadget` only works for plain pointers.

Please note that when deserializing a gadget pointer, it is internally allocated using `new` and thus must be deleted by the caller.

Even with this, polymorphic gadgets are not supported for the same reason as in #8. However, using gadget pointers will propably make it much easier to actually implement those in a project
