### ISSUE TITLE
(De-)Serializing outer enums

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#7]
Let's assume that we have an old C enum wrapped inside of the Q_GADGET struct:
```
struct MyEnumWrapper
{
 Q_GADGET
 //re-open public visibility after Q_GADGET
 public:
 enum Enum
 {
  unknown,
  one,
  two,
  three
 };
Q_ENUM(Enum)
};
```
Now we have another Q_GADGET struct which must be serialized. It contains field `MyEnumWrapper::Enum myEnumField; ` How  should Q_PROPERTY and other stuff like getter be organized for QtJsonSerializer?  I mean that I'd like to see stringified enum values. I am aware about `setEnumAsString(true);`.

**Comment by Skycoder42** [comment]
I'm not exactly shure what you are asking, but I'll try to answer anyways.

Where the Enum is defined does not really matter for serializing, as long as the `Q_ENUM` macro is used (which it is for your example). Now all that needs to be done is declare the `Q_PROPERTY` with the enums full qualified name as type:

```.cpp
struct MySecondGadget
{
    Q_GADGET

    Q_PROPERTY(MyEnumWrapper::Enum myEnumField MEMBER myEnumField)

public:
    MyEnumWrapper::Enum myEnumField;
};

Q_DECLARE_METATYPE(MySecondGadget)
```

To ensure it works as intended, you should also register the gadget wrapper as metatype (As you should do with all your gadgets). Use `Q_DECLARE_METATYPE(MyEnumWrapper)` in the header and `qRegisterMetaType<MyEnumWrapper>();` in your main.cpp. Finally, use the `setEnumAsString(true);` as you already mentioned, and your good to go.

**Note:** In case you have to use flags, use `Q_PROPERTY(MyEnumWrapper::Flags myflagsField READ getField WRITE setFiled)` instead, as member access for flags is broken. But for classic enums, using the member should suffice.

**Comment by arietto** [comment]
Thank you for your full answer. BTW, I've tried to disable  `Q_DECLARE_METATYPE(MyEnumWrapper)` and `qRegisterMetaType<MyEnumWrapper>();`. It worked even without them.

**Comment by Skycoder42** [comment]
Good to know. It's sometimes hard to know what works with the registrations and what not. Thats why I just always add them, to be on the safe side.
